# Generated by Django 5.1.7 on 2025-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='library_card_number',
        ),
        migrations.AddField(
            model_name='student',
            name='library_card_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
