# Generated by Django 5.1.7 on 2025-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dues',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
