# Generated by Django 5.1.7 on 2025-03-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_dues_librarian_can_apprvve_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarian',
            old_name='can_apprvve_borrow',
            new_name='can_approve_borrow',
        ),
    ]
