# Generated by Django 5.1.7 on 2025-03-14 05:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('genre', models.CharField(choices=[('Metallurgy', 'Metallurgy'), ('Computer Science', 'Computer Science'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('AI', 'AI'), ('Data Science', 'Data Science'), ('Mining', 'Mining'), ('IT', 'IT')], max_length=50)),
                ('topics', models.TextField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('journal_type', models.CharField(choices=[('Journal', 'Journal'), ('Magazine', 'Magazine'), ('Newspaper', 'Newspaper')], max_length=50)),
                ('publication_date', models.DateField()),
                ('issn', models.CharField(blank=True, help_text='Enter ISSN only for Journals', max_length=30, null=True, unique=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='journals', to='books.author')),
            ],
        ),
    ]
