# Generated by Django 5.1.7 on 2025-03-17 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('genre', models.CharField(choices=[('Metallurgy', 'METALLURGY'), ('Computer Science', 'CS'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mechanical', 'MECHANICAL'), ('Civil', 'CIVIL'), ('AI', 'AI'), ('Data Science', 'DATA SCIENCE'), ('Mining', 'MINING'), ('IT', 'IT')], max_length=50)),
                ('topics', models.TextField(blank=True, null=True)),
                ('available_copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('journal_type', models.CharField(choices=[('Journal', 'Journal'), ('Magazine', 'Magazine'), ('Newspaper', 'Newspaper')], max_length=50)),
                ('publication_date', models.DateField()),
                ('available_copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('issn', models.CharField(blank=True, help_text='Enter ISSN only for Journals', max_length=30, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
    ]
