# Generated by Django 5.1.7 on 2025-03-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Metallurgy', 'METALLURGY'), ('Computer Science', 'CS'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Mechanical', 'MECHANICAL'), ('Civil', 'CIVIL'), ('AI', 'AI'), ('Data Science', 'DATA_SCIENCE'), ('Mining', 'MINING'), ('IT', 'IT')], max_length=50),
        ),
    ]
