# Generated by Django 5.1.7 on 2025-03-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journal',
            name='available_copies',
            field=models.IntegerField(default=1),
        ),
    ]
