# Generated by Django 5.1.7 on 2025-03-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
