# Generated by Django 5.1.7 on 2025-03-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='authors',
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.book')),
            ],
            options={
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.CreateModel(
            name='JournalAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.journal')),
            ],
            options={
                'unique_together': {('journal', 'author')},
            },
        ),
    ]
