# Generated by Django 5.1.7 on 2025-03-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='librarian_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
