# Generated by Django 5.1.7 on 2025-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned'), ('Pending Return', 'Pending Return')], default='Pending', max_length=20),
        ),
    ]
