# Generated by Django 5.1.7 on 2025-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrowing_librarian_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='faculty_approved',
            new_name='admin_approved',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=10),
        ),
    ]
